// Currency Types
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';

// Cryptocurrency Types
export const FETCH_CRYPTO_LIST_REQUEST = 'FETCH_CRYPTO_LIST_REQUEST';
export const FETCH_CRYPTO_LIST_SUCCESS = 'FETCH_CRYPTO_LIST_SUCCESS';
export const FETCH_CRYPTO_LIST_FAILURE = 'FETCH_CRYPTO_LIST_FAILURE';

// Market Chart Types
export const FETCH_MARKET_CHART_REQUEST = 'FETCH_MARKET_CHART_REQUEST';
export const FETCH_MARKET_CHART_SUCCESS = 'FETCH_MARKET_CHART_SUCCESS';
export const FETCH_MARKET_CHART_FAILURE = 'FETCH_MARKET_CHART_FAILURE';

// Global Market Types
export const FETCH_GLOBAL_MARKET_REQUEST = 'FETCH_GLOBAL_MARKET_REQUEST';
export const FETCH_GLOBAL_MARKET_SUCCESS = 'FETCH_GLOBAL_MARKET_SUCCESS';
export const FETCH_GLOBAL_MARKET_FAILURE = 'FETCH_GLOBAL_MARKET_FAILURE';

// Exchange Rate Types
export const FETCH_EXCHANGE_RATE_REQUEST = 'FETCH_EXCHANGE_RATE_REQUEST';
export const FETCH_EXCHANGE_RATE_SUCCESS = 'FETCH_EXCHANGE_RATE_SUCCESS';
export const FETCH_EXCHANGE_RATE_FAILURE = 'FETCH_EXCHANGE_RATE_FAILURE';

// Search Types
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

// Selected Cryptocurrencies for Chart
export const ADD_SELECTED_CRYPTO = 'ADD_SELECTED_CRYPTO';
export const REMOVE_SELECTED_CRYPTO = 'REMOVE_SELECTED_CRYPTO';

// Chart Type
export const SET_CHART_TYPE = 'SET_CHART_TYPE';